---
# tasks file for win_ad_install
# installing the AD 

- name: Install AD-Domain-Services feature
  win_feature:
    name=AD-Domain-Services
    include_management_tools=yes
    include_sub_features=yes
    state=present

#Sets up the AD controller using the win_domain module

- name: Configure Domain Controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: ad_controllers

#Reboots the instance after configuration is complete using the win_reboot module

- name: reboot once controller created
  win_reboot:
  when: ad_controllers.reboot_required

#Prints out the domain list available after the reboot is complete using the nltest /dclist:"{{ ad_domain_name }}" shell command

- name: List DCs in domain
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domains

- debug:
    var: domains
